#最大公約数を求めるシェルスクリプト (gcd.sh):

bash
コードをコピーする
#!/bin/bash

# 引数の数が2でない場合、エラー終了
if [ "$#" -ne 2 ]; then
    echo "Error: 2つの自然数を引数として入力してください" >&2
    exit 1
fi

# 引数が自然数でない場合、エラー終了
if ! [[ $1 =~ ^[1-9][0-9]*$ && $2 =~ ^[1-9][0-9]*$ ]]; then
    echo "Error: 自然数を入力してください" >&2
    exit 1
fi

# 辞書順に並べ替える
a=$1
b=$2
if [ "$a" -lt "$b" ]; then
    tmp=$a
    a=$b
    b=$tmp
fi

# ユークリッドの互除法で最大公約数を求める
while [ "$b" -ne 0 ]; do
    tmp=$b
    b=$((a % b))
    a=$tmp
done

echo "$a"
